### ISSUE TITLE
`cachedEventHandler()` needs at least 2 calls after it is invalid

### ISSUE THREAD

**Issue by MickL** [unjs/nitro#1948] opened 2023-11-23 12:04 UTC
### Environment

Nuxt: 3.8.2
H3: 1.9.0
nitropack: 2.8.0
Server: Vercel
Storage: Vercel KV (Redis)

### Reproduction

server/api/tester.ts
```ts
export default cachedEventHandler(
  async (event): Promise<any> => {
    return Date.now();
  },
  {
    maxAge: 5, // seconds
  },
);
```

nuxt.config.ts
```
export default defineNuxtConfig({
  devtools: { enabled: true },
  nitro: {
    storage: {
      cache: {
        driver: 'vercelKV',
      },
    },
  },
});
```

### Describe the bug

Using `cachedEventHandler()` with Vercel KV (Redis) requires at least 2 calls after the cache is invalid until the function runs again:

1. GET request -> Function runs + is cached
2. GET request -> Returns cached response
3. Wait until `maxAge` is expired
4. GET request -> Returns cached response (should run the function instead)
5. GET request -> Function runs + is cached

### Additional context

In development Nitro is using the FS driver and I there it seems to work as it should.

**Comment by pi0** [comment] 2023-11-23 12:10
Hi. I made a minimal sandbox to reproduce: https://stackblitz.com/edit/github-avewtb?file=routes%2Findex.ts

It is in fact an expected behavior. By default, we enable Stable-While-Revalidate strategy. The response will be invalidated in the background that's why you immediately get the old one until this time passes. (but notice the log that handler is immediately invoked) 

If you wish to get response after handler resolved, you can disable SWR using `swr: false`

**Comment by MickL** [comment] 2023-11-23 12:24
Thanks for the super fast response! Shouldnt swr be disabled by default to prevent unexpected results and confusion? When the cache is invalid, I expect my handler function to run and return the new result immediately. Otherwise the cache seems broken to me. E.g. thinking about a button on a website that says "update" wouldnt return an updated result, isntead it would return the same cached data as before.

I made a minimal reproduction repo:
https://github.com/MickL/nuxt-nitro-cache

Deployed to Vercel using Vercel KV:
https://nuxt-nitro-cache.vercel.app/api/tester

Indeed within development (using FS driver) it reruns the function immediately. Maybe because on dev everything is so fast? This would mean that on dev it is "wrong" while on Vercel it is correct.

**Comment by pi0** [comment] 2023-11-23 12:33
PR welcome to clarify the docs 👍🏼 Benefits of SWR behavior for non-blocking responses was important enough that we initially decided on this default. We can discuss later to change it for next major versions of nitro if enough merits.

Yep maybe dev experience is fast enough so you haven't notice issue :p

With disabled `swr` do you still have issues with caching behavior on vercel?

---

Unrelated: Since saw `date-fns` in your example, consider it has a poor bundling result (for worker targets) (https://github.com/unjs/nitro/issues/1889)

**Comment by MickL** [comment] 2023-11-23 12:46
I would highly suggest swr default set to false as this creates unexpected behavior: The cache is invalid but still returned.

Updated the docs to make this more clear: https://github.com/unjs/nitro/pull/1949

**Comment by pi0** [comment] 2023-11-23 13:05
Lets move default discussion to https://github.com/unjs/nitro/issues/1950 

Thanks for docs PR.

Do we need to keep this issue still open?

**Closed** 2023-11-23 13:09 UTC
Labels: pending triage
