### ISSUE TITLE
Nitro tests do not run in folder with special characters (e.g. space)

### ISSUE THREAD

**Issue by manniL** [unjs/nitro#448] opened 2022-08-29 20:12 UTC
### Environment

WSL (Ubuntu 20.4) (also tested on classic windows)
Nitro repo from commit https://github.com/unjs/nitro/commit/d1d1015228f5297741951e596079900816241f50

### Reproduction

1. Create a folder `temp space`
2. `cd` into it
3. Clone the nitro repo
4. `pnpm i`
5. `pnpm t`

### Describe the bug

The tests fail to run because the server entrypoint (`index.mjs`) can't be found. Likely due to https://github.com/unjs/nitro/blob/main/src/prerender.ts#L33 + using e.g. spaces

**Comment by pi0** [comment] 2024-05-16 17:37
closing since issue is stalled. if you can stably reproduction please create new issue 🙏🏼

**Closed by pi0** 2024-05-16 17:37 UTC
Labels: bug
