### ISSUE TITLE
Support ignoring certain files in `./api` and `./routes`

### ISSUE THREAD

**Issue by joshmossas** [unjs/nitro#1183] opened 2023-04-23 07:48 UTC
### Describe the feature

I would like a way to prevent Nitro from generating endpoints for certain files in the `api` and `routes` directory. 

Nuxt supports this in the `pages` directory using either an [ignorePrefix](https://nuxt.com/docs/guide/directory-structure/nuxt.config#ignoreprefix) or a [.nuxtignore](https://nuxt.com/docs/guide/directory-structure/nuxtignore) file. Perhaps a similar configuration setting can be brought to nitro?

## Use Case

This would allow devs to co-locate common functionality next to the relevant endpoints.

```
Assume our ignorePrefix is "$"

| api
    | users
        |---- route-1.get.ts
        |---- route-2.post.ts
        |---- route-3.delete.ts
        |---- $common.ts   // this doesn't generate an endpoint because it has the ignorePrefix
```

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by joshmossas** [comment] 2023-04-23 07:49
Willing to help with the implementation when I get some free time. I've only briefly skimmed over the codebase, but is the primary implementation point related to this function in `scan.ts`? https://github.com/unjs/nitro/blob/7577528fd13c9540c1947702e74b1b29e84e22fc/src/scan.ts#L41

**Comment by Hebilicious** [comment] 2023-06-30 21:29
Hi @joshmossas, this is a duplicate of https://github.com/unjs/nitro/issues/843. Let's track over there.

**Closed by Hebilicious** 2023-06-30 21:29 UTC
Labels: duplicate
