### ISSUE TITLE
Deployment Overview page 404

### ISSUE THREAD

**Issue by ChrisScrumping** [unjs/nitro#1394] opened 2023-07-04 22:16 UTC
### Environment

https://nitro.unjs.io/

### Reproduction

Try going to https://nitro.unjs.io/deploy

### Describe the bug

When opening https://nitro.unjs.io/deploy or refreshing the page I get a 404 page not found.

### Additional context

Initially I discovered this by clicking a link to the page from here: https://nuxt.com/docs/getting-started/deployment#deployment

**Comment by Hebilicious** [comment] 2023-07-05 07:55
@Atinux I've seen this happening a few times in Nuxt/UnJS websites. Is this docus / Nuxt content related?

**Comment by ChrisScrumping** [comment] 2023-07-05 14:12
I have had it happen recently on a Nuxt app I am creating but it turned out to be a redirect issue on the server not Nuxt.

In this case though there does not appear to be any redirects happening, the server just returns a 404.

```curl -vv https://nitro.unjs.io/deploy/workers```

**Comment by JamieCurnow** [comment] 2023-07-06 20:07
I started looking into this. I couldn't reproduce locally...

Interestingly, I can reproduce the bug on vercel:
https://jamiecurnow-nitro-nomc9cbxu-jamiecurnow.vercel.app/deploy/workers

But when I deploy to Netlify it works perfectly:
https://stately-donut-53286f.netlify.app/deploy/workers/

Both the builds are using `npm run build` and looking at the `dist` directory for the public assets. I'll do some more digging tomorrow on node versions etc...

**Comment by JamieCurnow** [comment] 2023-07-07 08:10
@Hebilicious does nitro detect that it's in a vercel / netlify environment and apply build presets accordingly?

**Comment by JamieCurnow** [comment] 2023-07-07 09:26
I think I've found the cause... When doing a vercel preset build, most paths in the `.vercel/output/config.json` do not have a trailing slash. BUT the paths that don't work *do* have a trailing slash...

```
{
  "version": 3,
  "overrides": {
    "index.html": {
      "path": ""
    },
    "guide/getting-started/index.html": {
      "path": "guide/getting-started"
    },
    // ...
    "deploy/workers/index.html": {
      "path": "deploy/workers/" // <-- trailing slash
    },
  }
}
```

I've tested this by adding the following to the nuxt config:

```
nitro: {
    vercel: {
      config: {
        version: 3,
        overrides: {
          "deploy/index.html": {
            path: "deploy",
          },
          "deploy/workers/index.html": {
            path: "deploy/workers",
          },
        },
      },
    },
  },
```
And it works! 🥳 

Now to try to figure out why those trailing slashes are being added....

**Comment by Hebilicious** [comment] 2023-07-07 10:14
Nice catch @JamieCurnow, you're on fire. I looks like it happens with the pre-rendered routes because we're not removing the trailing slash here https://github.com/unjs/nitro/blob/6bc50b2f9416dc9af6ba327440deea2ec8e35a33/src/presets/vercel.ts#L164

**Comment by JamieCurnow** [comment] 2023-07-07 10:24
@Hebilicious it's not random - it's because of links. If I change this link here:
https://github.com/unjs/nitro/blob/main/docs/content/2.deploy/2.workers.md?plain=1#L23

From:
`[limitations](/deploy/workers/#limitations)`
to
`[limitations](/deploy/workers#limitations)`

Then we don't get multiple entries in `nitro._prerenderedRoutes`.

So I guess it's kind of working as it should...? But this would be a nightmare of a bug for a user to figure out so it feels like it should be handled in some way?

It's not affecting the netlify preset, but I wonder if it is affecting others?

Do you want me to make a PR for fixing it on the Vercel preset and we can just fix others if/when they come up? Or is this a deeper issue that should be handled further back in nitro?

**Comment by Hebilicious** [comment] 2023-07-07 13:55
Thanks for the great investigation ! 
I think we should remove the trailing slashes in the affected presets. 
Let's wait for what @pi0  has to say.

**Comment by 9mm** [comment] 2023-08-03 13:21
Seems good idea to fix this, im new to nitro and it is weird projects' own website doesnt even load 🤔

**Comment by hecktarzuli** [comment] 2023-08-28 13:48
@pi0 this caused my whole site to be removed from Google.  I have to think there are others out there too.

**Comment by pi0** [comment] 2023-08-29 10:03
Sorry for the troubles @hecktarzuli I will try to pick up this issue and investigate ASAP.

**Comment by Hebilicious** [comment] 2023-08-29 11:50
@pi0 Could we remove  the trailing slashes for the affected presets ?

**Comment by TheDevMinerTV** [comment] 2024-07-21 19:48
Still happening, it makes the docs unusable.

**Comment by pi0** [comment] 2024-10-04 13:05
Just checking, issue should be fixed.

**Closed by pi0** 2024-10-04 13:05 UTC
Labels: bug, documentation, good first issue, preset:vercel
