### ISSUE TITLE
webtorrent breaks rollup build in dev mode

### ISSUE THREAD

**Issue by nitedani** [unjs/nitro#244] opened 2022-05-16 03:22 UTC
### Environment

nitropack: 0.4.4
node: 16.13.2
no config

### Reproduction

1. create a new project
2. install webtorrent
3. add this code: 
```
import WebTorrent from "webtorrent";
const client = new WebTorrent();

export default () => "Hello World";
```
4. npx nitropack dev

### Describe the bug

Rollup errors, the server doesn't run.
All is fine and webtorrent works as expected with `npx nitropack build` and `node .output/server/index.mjs`
![image](https://user-images.githubusercontent.com/67418286/168514392-0add2bca-6ee0-459c-b028-557aaa8f63e4.png)
![image](https://user-images.githubusercontent.com/67418286/168514574-868ac53f-d6a1-4840-82f5-584dc214fcff.png)

**Comment by birdlavv** [comment] 2022-05-21 19:36
Possible duplicate of https://github.com/unjs/nitro/issues/200?

**Comment by pi0** [comment] 2024-05-16 17:13
Closing since the issue has been stalled for a long period. If experiencing issues with latest version of nitro, please feel free to open a new issue with a fresh reproduction 🙏🏼

**Closed by pi0** 2024-05-16 17:13 UTC
