### ISSUE TITLE
Support multiple function names in Firebase preset

### ISSUE THREAD

**Issue by snsxn** [unjs/nitro#1257] opened 2023-05-19 14:43 UTC
### Describe the feature

I'm currently using a regex to replace the name of the` export { s as server }`.

It would be nice to see a way to create different names in functions, allowing us to use Firebase project with multihosting out of the box

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by AlexLavoie42** [comment] 2023-06-10 01:47
I was able to get this to work using this config option

```js
replace: {
    'const server = functions.https.onRequest': 'const $NEW_NAME = functions.https.onRequest'
}
```

I would be interested in implementing this, but I'm not sure if there is a better option than using rollup replace. I was thinking of replacing `export const server` with something more distinct like `export const $FIREBASE_FUNCTION_NAME` and have `$FIREBASE_FUNCTION_NAME` replaced with `server` by default.

**Comment by Hebilicious** [comment] 2023-07-01 23:05
duplicate of #266 

Let's move the discussion there.

**Comment by Hebilicious** [comment] 2023-07-01 23:05
duplicate of #266 

Let's move the discussion there.

**Closed by Hebilicious** 2023-07-01 23:05 UTC
Labels: preset:firebase, feature request
