### ISSUE TITLE
Occurance of unhandledRejection

### ISSUE THREAD

**Issue by tobiasdiez** [unjs/nitro#251] opened 2022-05-19 21:21 UTC
### Environment

rc3

### Reproduction

n/a

### Describe the bug

In https://github.com/unjs/nitro/pull/212 you have asked me, when these unhandledRejection errors occur. Here are two instances:

```
[nitro] [dev] [unhandledRejection] Error: TypeInfo not known for "Query$2"
    at InternalDependencyContainer.construct (/workspace/JabRefOnline/node_modules/tsyringe/dist/cjs/dependency-container.js:263:23)
    at InternalDependencyContainer.resolve (/workspace/JabRefOnline/node_modules/tsyringe/dist/cjs/dependency-container.js:105:33)
    at resolvers$2 (file:///workspace/JabRefOnline/.nuxt/dev/index.mjs:596:22)
    at loadResolvers (file:///workspace/JabRefOnline/.nuxt/dev/index.mjs:971:5)
    at loadSchema (file:///workspace/JabRefOnline/.nuxt/dev/index.mjs:985:21)
    at file:///workspace/JabRefOnline/.nuxt/dev/index.mjs:1094:13
```
where the last line refers to https://github.com/JabRef/JabRefOnline/blob/8ebc92fc768c193ec00cdba7da8e8779b6635ac6/server/api/%5B...%5D.ts#L32

and
```
 ERROR  [unhandledRejection] Cannot set headers after they are sent to the client

  at new NodeError (node:internal/errors:371:5)
  at ServerResponse.setHeader (node:_http_outgoing:576:11)
  at sendError (node_modules/h3/dist/index.mjs:216:13)
  at nodeHandler (node_modules/h3/dist/index.mjs:375:15)
```

**Comment by pi0** [comment] 2022-05-20 12:29
Hi @tobiasdiez, and thanks for not forgetting about that and sharing when it happens! 

Well, actually the issue is in your implementation. You should never leave a promise unsupervised. In this case, you could do `configureTsyringe().then(() => { ... }).catch(error => { console.error('Error while executing configureTsyringe', error) })`

Unrelated: Why would you need overhead of all express and HTTP server to start an apollo server? It wouldn't even work without Node.js and I think there is a lighter version for apollo...

Regardless you can also use lazy functions to initiate server: (https://www.jsdocs.io/package/h3#defineLazyEventHandler)

```js
export default defineLazyEventHandler(async () => {
  // Do all async stuff on first API call 
  // H3 await first on this
  await configureTsyringe() 
  const server = ...
  return defineHandler(server)
})
```

I'm closing issue since is not directly related to Nitro. But feel free to ping me here or in Discord if could be of any further help.

**Closed by pi0** 2022-05-20 12:29 UTC
