### ISSUE TITLE
cloudflare modules

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#91] opened 2022-04-12 17:16 UTC
https://github.com/nuxt/nuxt.js/issues/11747

https://developers.cloudflare.com/workers/cli-wrangler/configuration#modules

Using this, we can natively use imports for chunks instead of using one entry (maybe behind a flag?)

~~An alternative might be using KV + eval but last time checked both `eval` and `importScripts` were forbidden due to security concerns they had. So it is probably the only way to use the native option.~~

**Note:** This is not replacing normal workers as is a paid service.

**Comment by Hebilicious** [comment] 2022-05-01 18:14
> **Note:** This is not replacing normal workers as is a paid service.

I'm not sure what you mean with this sentence... But I can confirm that eval is not supported : https://developers.cloudflare.com/workers/runtime-apis/web-standards/#javascript-standards

**Comment by warflash** [comment] 2022-05-04 22:39
I was going to open a issue for a cloudflare pages preset proposal based off of this https://github.com/unjs/nitro/discussions/110 discussion, but wanted to make sure it's not a duplicate of this one first. This issue is tagged as a preset proposal as well, though atleast to me `cloudflare modules` itself sound like a change from the existing old cloudflare workers syntax to to ES modules. Does this issue include a cf pages preset or should I open a seperate one which people can then be pointed at?

**Comment by potatopotaro** [comment] 2022-06-18 21:41
If the unjs/nitro team is willing to document a preferred approach to custom presets, I'd be more than happy to take a crack at the CF modules upgrade. Looking at the source code, it seems like a majority of the work would involve creating a runtime entry file, of which I'm moderately familiar with (since its primarily just a CF worker script/handler). Even just a few pointers from the unjs team would probably be enough; I can leave a simple gist link here rather than commit a new preset.

**Comment by Hebilicious** [comment] 2023-06-30 22:58
Closing as this landed with https://github.com/unjs/nitro/pull/681

**Closed by Hebilicious** 2023-06-30 22:58 UTC
Labels: preset proposal
