### ISSUE TITLE
`routeRules` cache config does not support using functions like `getKey` or `shouldInvalidateCache`

### ISSUE THREAD

**Issue by ptoussai** [unjs/nitro#977] opened 2023-02-22 16:12 UTC
```
    routeRules: {
      '/information/**': {
        cache: {
          getKey: () => 'information',
          maxAge: 1000
        }
      }
    }
```

Functions like `getKey` or `shouldInvalidateCache` are striped from the `runtimeConfig`.
It seems to be on purpose, possibly because the config is serialised.
The config does not mention such a limitation.

**Comment by VladStepanov** [comment] 2023-02-24 13:30
Looks like https://github.com/unjs/nitro/issues/937

**Comment by ptoussai** [comment] 2023-02-24 13:40
> Looks like #937

It's not the same. The properties likes `getKey ` are already supported by the cache, however they are removed from the config at build time. Issue #937 is about the ability to have a dynamic `routeRules ` configuration.

**Comment by dolbex** [comment] 2023-02-24 19:51
We would love to see resolution here as well. Not sure how to invalidate or bypass what nitro has with this bug. If anyone has insight I will buy you some beers 🍺

**Comment by max-arias** [comment] 2023-03-09 13:10
Does anyone know of a workaround for this?

**Comment by zhuoqi-chen** [comment] 2023-03-12 05:17
At first, `shouldInvalidateCache` key is there in `src/rollup/config.ts`.
https://github.com/unjs/nitro/blob/a6ce587f69c1d4520cd78c46b0059f48f1839b54/src/rollup/config.ts#L166-L174
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/12776732/224525767-46096a62-3a8a-43e6-b3b1-e837af60b5ad.png">


But, The **`runtimeConfig`** has been handled by **`JSON.stringify`**, so function values are lost.
https://github.com/unjs/nitro/blob/a6ce587f69c1d4520cd78c46b0059f48f1839b54/src/rollup/config.ts#L198-L203

At this moment, `_runtimeConfig` is a [POJO](https://en.wikipedia.org/wiki/Plain_old_Java_object)，Hopefully it will be fixed soon.
https://github.com/unjs/nitro/blob/a6ce587f69c1d4520cd78c46b0059f48f1839b54/src/runtime/config.ts#L6
<img width="722" alt="image" src="https://user-images.githubusercontent.com/12776732/224525408-4766c362-0ed6-403c-8afe-48dd5aad3f99.png">

**Comment by dolbex** [comment] 2023-03-13 13:30
Great find @zhuoqi-chen! This seems like a pretty big hole in Nitro - Anybody have any ideas on how we can address this?

**Comment by pi0** [comment] 2023-03-13 13:55
Hi. Sorry for late responding to this issue and for confusing with types. (fixing in #1047)

Route rules (and in general nitro/nuxt options) only accept serializable type and functions like `shouldInvalidateCache` are not possible. So this is not a bug...

I believe we should extend route rules API for serializable options like `invalidateHeaders` and `keyTemplate` if we have good usecases for it). 

Also there might be a way to specify/extend route rules via a nitro plugin (will share an example if could make)

**Closed** 2023-03-13 14:01 UTC
Labels: enhancement, discussion

**Comment by William-WFC** [comment] 2023-08-29 02:37
I find getKey still invalid in routeRules > cache, in nitro.config.js 
here is my config
```
nitro: {
        devStorage: {
            'v_pc': {
                driver: 'redis',
                /* redis connector options */
                port: 6379, // Redis port
                host: 'localhost', // Redis host
                db: 0, // Defaults to 0
                maxRetriesPerRequest: 2,
            },
        },
        routeRules: {
            '/**': {
                cache: {
                    name: 'my_name',
                    swr: false,
                    maxAge: 6 * 60,
                    base: 'v_pc',
                    getKey: () => 'hhhiii',
                },
            },
        },
    },
```
I console.log in here (in route-rules.mjs file), 
```
const config = useRuntimeConfig();
console.log('config.nitro.routeRules', config.nitro.routeRules)
const _routeRulesMatcher = toRouteMatcher(
  createRadixRouter({ routes: config.nitro.routeRules })
);
```
getKey is lost
```
config.nitro.routeRules {
  '/__nuxt_error': { cache: false },
  '/**': { cache: { name: 'my_name', swr: false, maxAge: 360, base: 'v_pc' } }
}
```
I guess this is a bug. getKey is lost In the process of delivery.

**Comment by moedong** [comment] 2023-09-08 15:59
<img width="726" alt="image" src="https://github.com/unjs/nitro/assets/12723410/389d2561-9b31-4b75-bb4c-ebe9d2fda197">

Is the writing here wrong?

**Comment by moedong** [comment] 2023-09-08 16:03
👆The order of merging the options is wrong, right? The getKey method of the parameter will always be overwritten by this fixed getKey method.

**Comment by unluckynelson** [comment] 2023-10-11 21:15
> 👆The order of merging the options is wrong, right? The getKey method of the parameter will always be overwritten by this fixed getKey method.

No not really, because getKey is extracted from opts on line 232

**Comment by lxccc812** [comment] 2024-05-11 10:11
@2.8.1  Still can’t use getKey, has anyone succeeded?
