### ISSUE TITLE
Nitro request context is not available. Enable the experimental flag

### ISSUE THREAD

**Issue by imcm7** [unjs/nitro#1818] opened 2023-10-10 17:47 UTC
### Environment

Nuxt 3 with auth module

### Reproduction

https://github.com/imcm7/nuxt-event

### Describe the bug

In plugin Nitro request context is not available.
If remove plugin and using the api/auth[...].ts file the useEvent() work.

**Comment by pi0** [comment] 2023-10-11 15:33
Hi can you please make a runnable reproduction? 🙏🏼 Also does this issue also happens when running in development mode or only in the production?

**Comment by imcm7** [comment] 2023-10-11 17:00
@pi0 https://github.com/imcm7/nuxt-event

**Comment by pi0** [comment] 2024-01-23 18:07
closing due to  lack of minimal reproduction.

**Closed by pi0** 2024-01-23 18:07 UTC
Labels: nuxt, needs reproduction, pending triage

**Comment by imcm7** [comment] 2024-01-23 18:25
You can close all and do nothing. I now want to see that framework any more.
