### ISSUE TITLE
routeRules > cache > getKey lost in the process of delivery

### ISSUE THREAD

**Issue by William-WFC** [unjs/nitro#1660] opened 2023-08-29 02:40 UTC
I read the issue https://github.com/unjs/nitro/issues/977 .
But I find getKey still invalid in routeRules > cache, in nitro.config.js 
here is my config
```
nitro: {
        devStorage: {
            'v_pc': {
                driver: 'redis',
                /* redis connector options */
                port: 6379, // Redis port
                host: 'localhost', // Redis host
                db: 0, // Defaults to 0
                maxRetriesPerRequest: 2,
            },
        },
        routeRules: {
            '/**': {
                cache: {
                    name: 'my_name',
                    swr: false,
                    maxAge: 6 * 60,
                    base: 'v_pc',
                    getKey: () => 'hhhiii',
                },
            },
        },
    },
```
I console.log in here (in route-rules.mjs file), 
```
const config = useRuntimeConfig();
console.log('config.nitro.routeRules', config.nitro.routeRules)
const _routeRulesMatcher = toRouteMatcher(
  createRadixRouter({ routes: config.nitro.routeRules })
);
```
getKey is lost
```
config.nitro.routeRules {
  '/__nuxt_error': { cache: false },
  '/**': { cache: { name: 'my_name', swr: false, maxAge: 360, base: 'v_pc' } }
}
```
I guess this is a bug. getKey is lost In the process of delivery. 
```[tasklist]
### Tasks
- [ ] https://github.com/unjs/nitro/issues/977
```

**Comment by pi0** [comment] 2023-08-29 10:15
Thanks for detailed issue dear @William-WFC but would you please also attach a minimal reproduction?

**Comment by William-WFC** [comment] 2023-08-30 10:58
> Thanks for detailed issue dear @William-WFC but would you please also attach a minimal reproduction?

here is reproduction.

https://stackblitz.com/edit/nuxt-starter-v6wnbq?file=nuxt.config.ts,app.vue

the cache file in .nuxt/cache/nitro/routes/my_test should be hhhiii.json, as configured in nuxt.config.ts. 
but actually it's index.il7asoJjJE.json

**Comment by unluckynelson** [comment] 2023-10-11 20:44
@William-WFC I have been looking at the same issue and the getKey parameter is removed by `normalizeRouteRules` in https://github.com/unjs/nitro/blob/main/src/options.ts#L424

**Comment by lxccc812** [comment] 2024-05-14 03:32
Is there any answer?

**Comment by MiniDigger** [comment] 2024-05-14 07:03
I think this is a duplicate of https://github.com/unjs/nitro/issues/1048

**Comment by pi0** [comment] 2024-05-14 09:26
Let's track with https://github.com/unjs/nitro/issues/1048

non serializable values in route rules such as functions cannot be passed from config to runtime.

**Closed by pi0** 2024-05-14 09:26 UTC
Labels: nuxt, needs reproduction
