### ISSUE TITLE
Deno preset deploy faild to run

### ISSUE THREAD

**Issue by aramdata** [unjs/nitro#2022] opened 2023-12-24 14:16 UTC
### Environment

node 18 , Nuxt 3.8.2 with Nitro 2.8.1
ℹ Using Nitro server preset: deno_deploy

### Reproduction

pnpm run build --preset=deno_deploy ==> create index.ts in server folder 
deno run -A server\index.ts => raise error , error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'match')
  const match = input.match(SEMVER_REGEXP) || [];

### Describe the bug

in my index.ts file there is line for node version 
`
const NODE_VERSION = utils$D.parseSemver(process.versions.node);
`
that pass  ` process.versions.node ` to method 
`
function parseSemver(input) {
  const match = input.match(SEMVER_REGEXP) || [];
  const major = parseInt(match[1], 10);
  const minor = parseInt(match[2], 10);
  const patch = parseInt(match[3], 10);
  return {
    buildmetadata: match[5],
    major: isNaN(major) ? undefined : major,
    minor: isNaN(minor) ? undefined : minor,
    patch: isNaN(patch) ? undefined : patch,
    prerelease: match[4],
  };
}
`

input is undefined.
in manual test , i replace const NODE_VERSION to 18 and deno run worked.

**Comment by DavidDeSloovere** [comment] 2024-01-03 16:42
I've got similar issue with Nuxt 3.9 + Cloudflare pages + sentry packages (started adding this).

So it looks like a 'non-Node runtime', seeing it's both Deno and Cloudflare.

Building with cloudflare_pages preset is no problem. But when the project is built by Cloudflare pages itself, the error is thrown. 


`Error: Failed to publish your Function. Got error: Uncaught TypeError: Cannot read properties of undefined (reading 'match')   at chunks/nitro/cloudflare-pages.mjs:714:19300 in pa.parseSemver   at chunks/nitro/cloudflare-pages.mjs:714:228160`


Locally I can get the same error after running the built application with `npx wrangler pages dev dist/`.

```
X [ERROR] service core:user:worker: Uncaught TypeError: Cannot read properties of undefined (reading 'match')

    at null.<anonymous> (ic6cnwf64jr.js:43795:22) in ga2.parseSemver
    at null.<anonymous> (ic6cnwf64jr.js:48539:14) in
  .wrangler/tmp/pages-LZOvk4/chunks/nitro/cloudflare-pages.mjs
    at null.<anonymous> (ic6cnwf64jr.js:11:59) in __init
    at null.<anonymous> (ic6cnwf64jr.js:50502:1)
```

I don't think I can fix this, but I can help test this.

**Comment by DavidDeSloovere** [comment] 2024-01-04 16:22
I will try to create a reproduction tomorrow.

**Comment by DavidDeSloovere** [comment] 2024-01-05 10:23
I found the cause of my error, it's the sentry package that want to read the nodejs version.
https://github.com/getsentry/sentry-javascript/blob/develop/packages/node/src/nodeVersion.ts

@aramdata Are you using any packages that just might not run on Deno?

**Comment by pi0** [comment] 2024-01-05 10:28
A reproduction would be nice to help resolving this 🙏🏼

**Comment by aramdata** [comment] 2024-01-06 08:53
> I found the cause of my error, it's the sentry package that want to read the nodejs version. https://github.com/getsentry/sentry-javascript/blob/develop/packages/node/src/nodeVersion.ts
> 
> @aramdata Are you using any packages that just might not run on Deno?

yes i using sentry package too , and when remove this dependency it work fine in windows but now in docker ci workflow  not work and different compiled ts . i decide to build in node_cluster mode preset for multiple instance runtime.

**Comment by DavidDeSloovere** [comment] 2024-01-06 12:34
It think we can safely say taht it's not a Nitro bug?
If you agree, you can close this issue to save Pooya some work ;-)

**Comment by zacwebb** [comment] 2024-04-16 05:27
Had the same thing happening to me with `@sentry/node` when deploying on Cloudflare pages:

```
Error: Failed to publish your Function. Got error: Uncaught TypeError: Cannot read properties of undefined (reading 'match')
at chunks/runtime.mjs:1:143409 in Kn.parseSemver   at chunks/runtime.mjs:1:379456
```

Removing `@sentry/node` seemed to sort it. Like @DavidDeSloovere said this issue can probably be closed as the issue is upstream

**Closed** 2024-04-22 07:27 UTC
Labels: nuxt, needs reproduction, pending triage
