### ISSUE TITLE
cloudflare-pages-static with Functions

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#196] opened 2022-05-05 09:16 UTC
Reference: nuxt/framework#110

> @[warflash](https://github.com/warflash)
> Cloudflare pages for static assets + [functions](https://blog.cloudflare.com/cloudflare-pages-goes-full-stack/) for ssr and dynamic content would be awesome!

**Comment by warflash** [comment] 2022-05-05 11:13
Nice! Really looking forward to that.

Related discussions for easy future reference:
https://github.com/nuxt/framework/discussions/2471
https://github.com/nuxt/framework/discussions/1528
https://github.com/unjs/nitro/discussions/110

@DaniFoldi 🎉

**Comment by DaniFoldi** [comment] 2022-05-05 11:17
I'll look into implementing this sometime this week (I have a test repo that _works_), probably create a draft PR, would be very helpful if someone with more nitro knowledge could take a look

**Comment by DaniFoldi** [comment] 2022-05-07 11:09
@warflash I've got #210 drafted, looking for feedback now

**Comment by warflash** [comment] 2022-05-07 11:52
Awesome, great work!
I can't give much feedback on the preset itself but what I did notice is the use of `_workers.js`.
That reminded me of a conversation on the [cloudflare discord](https://discord.com/channels/595317990191398933/967071916160610344/970000768667090954) I read:

> Functions in particular has been interesting (to me, at least). SvelteKit opted for using _worker.js, whereas Remix and Qwik have opted for functions/[[all]].ts.
Plugins should technically work with the later two, but won’t (currently) with SvelteKit, because of that decision. Maybe we encourage SvelteKit to move to the functions folder, or maybe we offer some other way into the Plugins ecosystem. Haven’t quite worked that bit out yet.

That makes it sounds like `functions/[[all]].ts` is the recommended way forward. I haven't used plugins yet nor am I experienced with nitro presets so I'm not sure how big of a change that is, just figured I'd drop it here.

Again, nicely done 🚀

**Comment by AlexDicy** [comment] 2022-05-07 12:00
> Awesome, great work!
> I can't give much feedback on the preset itself but what I did notice is the use of `_workers.js`.
> That reminded me of a conversation on the [cloudflare discord](https://discord.com/channels/595317990191398933/967071916160610344/970000768667090954) I read:
> 
> > Functions in particular has been interesting (to me, at least). SvelteKit opted for using _worker.js, whereas Remix and Qwik have opted for functions/[[all]].ts.
> Plugins should technically work with the later two, but won’t (currently) with SvelteKit, because of that decision. Maybe we encourage SvelteKit to move to the functions folder, or maybe we offer some other way into the Plugins ecosystem. Haven’t quite worked that bit out yet.
> 
> That makes it sounds like `functions/[[all]].ts` is the recommended way forward. I haven't used plugins yet nor am I experienced with nitro presets so I'm not sure how big of a change that is. Figured I'd drop it here in case that's something that's required in the future or when there's people asking about it.
> 
> Again, nicely done 🚀

I agree. I've also noticed that the code doesn't mention the filename to use when compiling the server.

With my implementation I had to rename the server file from `index.mjs` to `_workers.js` (and move it to /public), how is this handled in this PR?

**Comment by DaniFoldi** [comment] 2022-05-07 13:21
Correct, should be `functions/[[all]].ts` for plugin compatibility. Bear in mind plugins are very new, and weren't a thing when I first started experimenting with this combo 😅

Note to future self: In that case we could also have `functions/` as the server output directory

**Comment by warflash** [comment] 2022-05-07 22:58
Oh actually something else to note on the `_workers.js` vs. `functions/[[all]].ts` topic, currently all static asset requests count as function invocations it seems. Though supposedly that will change once pages go out of beta (maybe we'll already see that with next weeks platform week). After beta only actual `functions/[[all]].ts` calls are billable whereas `_workers.js`  still proxies every static asset. Atleast that's my understanding of the conversations I read. 
Maybe @geelen has more insight on that one 🤞

**Comment by DaniFoldi** [comment] 2022-05-12 21:34
@geelen Is the API for this known (even if not yet implemented/available)? If so, would you mind sharing some more details so this PR can implement it properly?

**Comment by geelen** [comment] 2022-05-13 09:13
It'll be quite similar to [tsconfig include/exclude](https://www.typescriptlang.org/tsconfig#include=) but the exact wildcard support is not finalised as we need to do some perf testing on a couple of options. Had to be paused while we were finishing off a few other things (https://blog.cloudflare.com/tag/cloudflare-pages/ top 3 links all landed this week).

For now, it's a super good idea if all/most of your assets are under a prefix like `/static/*` or all your dynamic routes are under a prefix like `/api/*`. The fewer lines in your `_routes.json` the better, but we're trying to make it fast enough so it's still good if static and dynamic routes are fully intermingled.

**Comment by DaniFoldi** [comment] 2022-06-14 20:35
Quick update from my side, I have `@danifoldi/nitropack` published to npm for testing (do **not** use for anything other than a test, I intend to unpublish in a few months). 

Check [https://nitro-pages-functions.pages.dev/route](https://nitro-pages-functions.pages.dev/route) for a nitro-rendered page and [https://nitro-pages-functions.pages.dev/test](https://nitro-pages-functions.pages.dev/test) for a Pages-served static asset. This repo also uses the overrided nitropack to allow some real-world tests.

There's probably something that still won't work, and there will be a bit more work once Functions are in GA and include/exclude system mentioned above can be used to pass static asset requests directly to Pages. Let me know if(when) you find any bug, or anything else that's missing.

**Comment by Rigo-m** [comment] 2022-06-23 10:09
@DaniFoldi  have you tried deploying nuxt3 by resolving nitropack to your npm repository and deploy it to cloudflare pages?  I would like to try it

**Comment by DaniFoldi** [comment] 2022-06-24 09:12
@Rigo-m I haven't tried nuxt yet, just a nitro page.

I want to add the documentation first, and we're still working with @danielroe on how to pass bindings to the handlers.

**Comment by gacek1123** [comment] 2022-08-09 21:21
Is it still being worked on? Having this preset would be awesome

**Comment by gacek1123** [comment] 2022-09-05 13:05
@pi0 I think that this issue can now be closed since it got implemented

**Comment by ricky11** [comment] 2022-09-09 01:57
Im having problems with nuxt server/api/function routes not being copied over to the /functions folder when deployed to cloudflare.
I recreated a repo here : https://stackblitz.com/edit/github-dxg5qg?file=server%2Fapi%2Fcustomer.get.js
when i run`CF_PAGES=1 npm run generate' this creates a /functions directory but nothing in it, empty. 
according to nitro docs, the preset will be automatically detected.  Even when setting preset to cloudflare_pages, the functions folder is still empty...

**Comment by marvincaspar** [comment] 2022-09-13 08:58
I get an error if I try to generate a nuxt app with `NITRO_PRESET=cloudflare_pages`. 

```
ERROR  Cannot find module '/Users/mca/dev/private/nuxt-cloudflare/functions/index.mjs' imported from /Users/mca/dev/private/nuxt-cloudflare/node_modules/nitropack/dist/shared/nitro.ce47800e.mjs                  07:26:15

  at new NodeError (node:internal/errors:387:5)
  at finalizeResolution (node:internal/modules/esm/resolve:429:11)
  at moduleResolve (node:internal/modules/esm/resolve:1006:10)
  at defaultResolve (node:internal/modules/esm/resolve:1214:11)
  at nextResolve (node:internal/modules/esm/loader:165:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:844:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:18)
  at ESMLoader.import (node:internal/modules/esm/loader:528:22)
  at importModuleDynamically (node:internal/modules/esm/translators:110:35)
  at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Repo to reproducte the error https://github.com/marvincaspar/nuxt-cloudflare.

There is already an issue in nuxt framwork https://github.com/nuxt/framework/issues/7402

**Comment by ricky11** [comment] 2022-09-21 00:50
Adding issue [497](https://github.com/unjs/nitro/issues/497)
cloudflare_pages preset does preset does not transpile the /server/api folder in to cf pages /funtions
i believe that was the intention.

**Comment by marshallswain** [comment] 2022-11-17 23:50
I did a bunch of research for building a `cloudflare-esm` module.  I didn't have Pages Functions in mind at the time, but I'm linking in this discussion I started in the nuxt/framework repo since it may contain information applicable to creating a `cloudflare-pages` deployment preset: https://github.com/nuxt/framework/discussions/5487.

**Comment by iBobik** [comment] 2023-05-31 13:00
I needed static generated website + functions in /api. This works:

`package.json`, Clouflare configured to run `npm run cloudflare`:
```
{
  "scripts": {
    "cloudflare": "NITRO_PRESET=cloudflare_pages nuxt build && mv dist dist-build && nuxt generate && mv dist-build/_worker.js dist/",
```
`public/_routes.json` ([default config](https://github.com/unjs/nitro/blob/2ad43894a6039207fd535d7fdc30ba92d4847ee6/src/presets/cloudflare-pages.ts#L48) sends all traffic trhu the worker):
```
{
  "version": 1,
  "include": [
    "/api/*"
  ],
  "exclude": []
}

```

It would be nice if default preset could do this by default, or there will be config for it.

**Comment by Hebilicious** [comment] 2023-06-02 17:26
It looks like that throughout the year, cloudflare pages and workers will be merged into one service : https://blog.cloudflare.com/pages-and-workers-are-converging-into-one-experience/

There's not much information yet, but I assume everything will work with worker.toml, and that there won't be a need for a cloudflare pages preset anymore.

**Closed** 2024-05-16 16:48 UTC
Labels: pending, preset proposal

**Comment by iBobik** [comment] 2024-08-13 16:49
@pi0 Could you please link how this was completed? Still broken there.

**Comment by pi0** [comment] 2024-08-13 16:54
@iBobik `cloudflare-pages` preset. if you have a issue with documented behavior not working as expected, please consider opening a new issue with reproduction steps 🙏🏼

**Comment by iBobik** [comment] 2024-08-13 18:11
Not sure if it is related to Nitro, so posted repro there.
https://github.com/nuxt/nuxt/issues/28526
