### ISSUE TITLE
Pass ctx in preset cloudflare-pages

### ISSUE THREAD

**Issue by domlen2003** [unjs/nitro#773] opened 2022-12-20 18:37 UTC
### Describe the feature

In the preset fore cloudflare-pages there already seems to be a TODO for adding the cf context in the [File](https://github.com/unjs/nitro/blob/main/src/runtime/entries/cloudflare-pages.ts) was originally implemented by @DaniFoldi 

This would really help me with my current nuxt projekt where i really need a KV binding. 
In the normal cloudflare-functions adapter this is already possible tho our whole project is based on cloudflare-pages. 

### Additional information

- [x] Would you be willing to help implement this feature?

**Comment by domlen2003** [comment] 2022-12-20 19:10
I just saw this is probably not the ctx but the env. Anyway the cf datastore options should be available

**Comment by domlen2003** [comment] 2022-12-20 22:02
Since there is no easy way to pass context to an event handler (every additional info given in the adapter gets dropped in unenv/runtime/fetch/call.ts callHandle, when creating req) 

I would suggest adding:
`Object.entries(ctx.env).forEach(([k, v]) => process.env[k] = v)`
just before invoking the call in the adapter.

This would make it somewath similar to the context.env version in pages functions.

**Comment by dario-piotrowicz** [comment] 2023-01-30 11:08
PS: I think this issue is a duplicate of https://github.com/unjs/nitro/issues/391

**Comment by manniL** [comment] 2023-01-30 11:10
Let's track in https://github.com/unjs/nitro/issues/773 then

**Comment by dario-piotrowicz** [comment] 2023-02-19 16:08
@manniL sorry about the confusion but this issue is different from #391 and it hasn't been resolved by #677

I've got confused by the `context` terminology, but anyways in the other issue/PR they were referring to the `cf` object present in requests' headers but the context mentioned in this issue is different (is the one needed to access Cloudflare bindings)

could you please reopen this issue? :pray:

**Comment by Hebilicious** [comment] 2023-07-02 03:01
Fixed by https://github.com/unjs/nitro/pull/1004

**Closed by Hebilicious** 2023-07-02 03:01 UTC
Labels: pending triage
