### ISSUE TITLE
seems nitro taks a build stage bug

### ISSUE THREAD

**Issue by KahrLu** [unjs/nitro#413] opened 2022-08-11 10:20 UTC
### Environment

live, nuxt3-rc6

### Reproduction

![image](https://user-images.githubusercontent.com/76502123/184113234-ca893940-e716-4832-9f75-828b7d019df5.png)

### Describe the bug

![Uploading image.png…]()

**Comment by KahrLu** [comment] 2022-08-11 10:22
Hi @pi0 , sincethe last commit as nitro version 0.4.21 submitted 24minutes ago, my next publish was down.
the error is like above image

**Comment by KahrLu** [comment] 2022-08-11 10:28
Can we decide the nitro version using in nuxt3 by ourselves? we have meet three times build error with the reason of nitro upgrade in last two months

**Comment by danielroe** [comment] 2022-08-11 10:30
Fix should be in `0.4.21` ... Are you sure you are using it?

And yes, you can of course specify your own nitro version in your `package.json`.

**Comment by pi0** [comment] 2022-08-11 10:34
The issue is fixed in 0.4.22 sorry for regressions.

You can use resolutions (or a lockfile!) to fix nitro version but will also lose benefit of all fixes are being introduced in parallel to nuxt.

**Comment by KahrLu** [comment] 2022-08-11 10:34
> Fix should be in `0.4.21` ... Are you sure you are using it?
> 
> And yes, you can of course specify your own nitro version in your `package.json`.

is the package key named "nitropack"?

**Closed by pi0** 2022-08-11 10:34 UTC

**Comment by KahrLu** [comment] 2022-08-11 10:36
> The issue is fixed in 0.4.22 sorry for regressions.
> 
> You can use resolutions (or a lockfile!) to fix nitro version but will also lose benefit of all fixes are being introduced in parallel to nuxt.

thanks! I just wanted to say that 0.4.21 has same issue

**Comment by pi0** [comment] 2022-08-11 10:43
> is the package key named "nitropack"?

It is nitropack. But since is a sub-dependency, directly adding as dependency or devDependency cannot guarantee nuxt using it. You should use `resolutions` filed (using yarn) or `overrides` (using npm) or `pnpm.overrides` (using pnpm) to do so.
