### ISSUE TITLE
Proxy breaks images

### ISSUE THREAD

**Issue by jd1378** [unjs/nitro#1237] opened 2023-05-15 11:22 UTC
### Environment

nuxt 3 with nitro 2.4.0, node v18.14.2

### Reproduction

https://stackblitz.com/edit/github-xzp2dt?file=nuxt.config.ts,app.vue

(stackblitz doesn't allow external requests probably, but you get the idea, it still doesn't work locally)

### Describe the bug

When data is json, it works fine
but when data is image, it still return `{}` as image

### Additional context

example config (used in reproduction):
```ts
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  routeRules: {
    '/nuxt/**': {
      proxy: {
        to: 'https://nuxt.com/**',
      },
    },
  },
});
```

### Logs

the original problem (not reproduction) fails silently, so there's no log, log below is from stackblitz not being able to proxy requests

```sh
[3:16:32 PM] [nuxt] [request error] [unhandled] [500] request to https://nuxt.com/socials/composables.jpg failed, reason: socket hang up (https://nuxt.com/socials/composables.jpg)
  at async $fetchRaw2 (file://./node_modules/ofetch/dist/shared/ofetch.502a4799.mjs:197:24)  
  at async sendProxy (file://./node_modules/h3/dist/index.mjs:607:20)  
  at async Object.eval [as handler] (file://./node_modules/h3/dist/index.mjs:1348:19)  
  at async Server.toNodeHandle (file://./node_modules/h3/dist/index.mjs:1423:7)
```

**Comment by jd1378** [comment] 2023-05-15 12:24
so I went deep and used node debugger to see whats going wrong

It's a problem with h3's proxy somehow

I edited `node_modules\h3\dist\index.mjs` where this was the original:
```js
if (response._data !== void 0) {
    return response._data;
}
```
to 
```js
 if (response._data) {
    await response._data.arrayBuffer().then(b => {
      const buffer = Buffer.from(b);
      event.node.res.write(buffer);
    });
    return event.node.res.end();
  }
```

with this change, it now loads the image, but every other request (1 request fails, 1 succeeeds)

so Somehow, somtimes, `response._data` becomes `''` (empty)

I'm still digging to see what's wrong, but this should help a bit

**Comment by pavloniym** [comment] 2023-05-26 18:53
Confirmed.
If server response is 200 -> everything is okay
(This is console.log of `const response = await _getFetch(...)` of `async function sendProxy(event, target, opts = {})` in `h3/dist/index.mjs`)

```js
{
  response: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 200,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'OK',
      headersList: [HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}
```

If server response is 304 (not modified) -> proxy crashes

```js
{ 
  response: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 304,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Not Modified',
      headersList: [HeadersList],
      urlList: [Array],
      body: null
    },
    [Symbol(headers)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}
```

As you can see:
1. status is `304`
2. body is `null`

Also, I get this error:
```
[nuxt] [request error] [unhandled] [500] Cannot read properties of null (reading 'Symbol(Symbol.asyncIterator)')                  
  at sendProxy (./node_modules/h3/dist/index.mjs:583:38)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.handler (./.nuxt/dev/index.mjs:560:14)
  at async Object.handler (./node_modules/h3/dist/index.mjs:1278:19)
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1353:7)
```

**Comment by pavloniym** [comment] 2023-05-26 19:43
After some research i found fix:

```js

if (key === 'cf-ray' || key === 'etag' || key === 'last-modified') {
    continue
}

event.node.res.setHeader(key, value)
```

I just ignore some cache headers! (`cf-ray`, `etag`, `last-modified` in my case)  in `sendProxy` function of `h3/dist/index.mjs`

Now server with my images responds with 200 status code every request.
My suggestion is to add `ignoreResponseHeaders` option to `proxyRequest` and `sendProxy` functions to make this behaviour more customizable by developer OR wait until [this feature will be merged](https://github.com/unjs/h3/pull/368)

**Comment by jd1378** [comment] 2023-06-09 08:35
to tell the browser to use the cached copy of the resource, you want to keep responding with 304, not 200
making it all 200 is not the correct solution

**Comment by lvreninfo** [comment] 2023-06-26 08:28
My nuxt.config.ts file is configured like this, but it does not work. What can I do to implement the Reverse proxy of the image (I hope it will work in the official environment)?Please give me some advice. Thank you very much
```
export default defineNuxtConfig({
  nitro: {
    routeRules: {
      '/images/**': {
        proxy: {
          to: 'https://www.xxxx.com/images/**',
          headers: {
            'Host': 'www.xxxx.com'
          }
        }
      },
    }
  }
})
```

**Comment by jd1378** [comment] 2023-06-26 10:16
@lvreninfo you have to wait until it's fixed or patch you local version of package for now
Right now it's broken

**Comment by dickofn** [comment] 2023-07-25 11:08
> @lvreninfo you have to wait until it's fixed or patch your local version of package for now Right now it's broken

is this fixed in 1.7.1 or next build?

**Comment by jd1378** [comment] 2023-07-25 12:09
It's not in 1.7.1, and it doesn't seem to have a next build, so we have to wait till h3 releases a new version

**Comment by pi0** [comment] 2023-08-01 12:34
Please consider trying with [nitro edge](https://nitro.unjs.io/guide/getting-started#edge-release-channel) channel (it already includes h3 rc. you do **not** need nightly anymore). And please ping me to reopen if still having issues on nightly 🙏🏼

**Closed by pi0** 2023-08-01 12:34 UTC
Labels: bug, proxy

**Comment by jd1378** [comment] 2023-08-01 14:21
@pi0  when using 
```
  "resolutions": {
       "nitropack": "npm:nitropack-edge@latest"
  }
```
in package.json, the server throws `500, Cannot read properties of undefined (reading 'pathname')`:
``` 
500
Cannot read properties of undefined (reading 'pathname')

at getRouteRules ([removed]/.nuxt/dev/index.mjs:630:29)
at Object.handler ([removed]/.nuxt/dev/index.mjs:595:24)
at Object.handler ([removed]/node_modules/h3/dist/index.mjs:1284:31)
at toNodeHandle ([removed]/node_modules/h3/dist/index.mjs:1359:17)
at callHandle ([removed]/node_modules/unenv/runtime/fetch/call.mjs:24:12)
at ufetch ([removed]/node_modules/unenv/runtime/fetch/index.mjs:9:23)
at Object.localFetch ([removed]/.nuxt/dev/index.mjs:1012:12)
at errorhandler ([removed]/.nuxt/dev/index.mjs:704:50)
at Object.onError ([removed]/.nuxt/dev/index.mjs:1002:14)
at Server.toNodeHandle ([removed]/node_modules/h3/dist/index.mjs:1366:27)
```

same thing when I changed nuxt version in my dev deps to nuxt edge

**Comment by pi0** [comment] 2023-08-01 14:24
Have you treid to remove lockfile and node_modules? It should resolve problem.

**Comment by jd1378** [comment] 2023-08-01 14:24
I tried removing lockfile, but not node_modules
I had tried removing both when trying h3 nightly though, same error

**Comment by jd1378** [comment] 2023-08-01 14:29
tried removing both, getting the same error

**Comment by pi0** [comment] 2023-08-01 14:33
The issue is certainly because an older version of h3 is being used. Let me open PR in nuxt to make one testable edge channel (you are using nuxt right?)

**Comment by jd1378** [comment] 2023-08-02 14:26
@pi0 any news ?

**Comment by Hebilicious** [comment] 2023-08-02 14:58
> @pi0 when using
> 
> ```
>   "resolutions": {
>        "nitropack": "npm:nitropack-edge@latest"
>   }
> ```
> 
> in package.json, the server throws `500, Cannot read properties of undefined (reading 'pathname')`:
> 
> ```
> 500
> Cannot read properties of undefined (reading 'pathname')
> 
> at getRouteRules ([removed]/.nuxt/dev/index.mjs:630:29)
> at Object.handler ([removed]/.nuxt/dev/index.mjs:595:24)
> at Object.handler ([removed]/node_modules/h3/dist/index.mjs:1284:31)
> at toNodeHandle ([removed]/node_modules/h3/dist/index.mjs:1359:17)
> at callHandle ([removed]/node_modules/unenv/runtime/fetch/call.mjs:24:12)
> at ufetch ([removed]/node_modules/unenv/runtime/fetch/index.mjs:9:23)
> at Object.localFetch ([removed]/.nuxt/dev/index.mjs:1012:12)
> at errorhandler ([removed]/.nuxt/dev/index.mjs:704:50)
> at Object.onError ([removed]/.nuxt/dev/index.mjs:1002:14)
> at Server.toNodeHandle ([removed]/node_modules/h3/dist/index.mjs:1366:27)
> ```
> 
> same thing when I changed nuxt version in my dev deps to nuxt edge

Are you using npm ? `resolutions` is only supported by yarn and pnpm. For npm it's `overrides`.

**Comment by pi0** [comment] 2023-08-02 15:04
@Hebilicious issue is nuxt>h3 dependency

Using resolutions (or overrides) you can now try with h3 rc:


```json
{
  "resolutions": {
    "h3": "npm:h3@1.8.0-rc.2"
  }
}
```

**Comment by jd1378** [comment] 2023-08-02 15:34
I use yarn
I'll test and tell you the results

**Comment by jd1378** [comment] 2023-08-02 15:43
@pi0 
I'm getting another error now (I have removed lock file + node_modules)
```
Nuxi 3.7.0-28182870.7489b7d7                                                                                                 7:11:03 PM
Nuxt 3.7.0-28182870.7489b7d7 with Nitro 2.6.0-28182669.451d314                                                               7:11:03 PM

 ERROR  Cannot start nuxt:  The requested module '@vue-macros/common' does not provide an export named 'getTransformResult'  7:11:04 PM

  getTransformResult,
  ^^^^^^^^^^^^^^^^^^
  SyntaxError: The requested module '@vue-macros/common' does not provide an export named 'getTransformResult'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
  ```

**Comment by jd1378** [comment] 2023-08-04 01:06
I tried doing it again today and it worked this time

**Comment by jd1378** [comment] 2023-08-04 10:23
@pi0 something is broken, don't know the source of the problem. I get the following error when sending a request:
```
[nuxt] [request error] [unhandled] [500] fetch failed (<removed>/api/login)                                         1:40:44 PM
  at async sendProxy (/<removed>/node_modules/h3/dist/index.mjs:937:20)
  at async Object.handler (/<removed>/node_modules/h3/dist/index.mjs:1608:19)
  at async Server.toNodeHandle (/<removed>/node_modules/h3/dist/index.mjs:1819:7)
 ```
 which is not helpful at all to pin point the issue
 
 I went deeper to see where's the problem and this is where it throws in ofetch:
 
![image](https://github.com/unjs/nitro/assets/6196533/22d67e89-25d4-4863-9ab5-88b6c8fec480)

 what's weird is that when sending a request directly to the proxy, it succeeds, but when it's sent from browser, it is not. I tried setting exact same stuff in browser as in my standalone http client.
 this is the fetch I used in browser for reference: 
```
 fetch("/api/login", {
  "headers": {
    "accept": "application/json",
  },
  "body": "{\"email_or_mobile_number\":\"someemail@example.com\",\"password\":\"somepassword\"}",
  "method": "POST",
});
```
 
I tried going back and forth between nuxt 3.6.5 and edge with h3 1.8.0-rc.2 and I can confirm that it's working as expected in 3.6.5 without latest h3, but it's not working on edge and h3 1.8.0-rc.2

I can provide more info if needed

**Comment by jd1378** [comment] 2023-08-04 10:25
actually it's not exact same stuff, in fact it's what $fetch was sending when body was passed an object,
I'm using hoppscotch as my standalone httpclient and im setting parameters using it's parameters' section

**Comment by jd1378** [comment] 2023-08-04 10:40
I tried removing lock file and node_modules just in case anything is corrupted somehow and installed packages again but issue persists
